version: '3'
services:
  php:
    build: ./docker/php
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      # php.ini
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      # apache
      - ./docker/php/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: sample
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  selenium-hub:
      image: selenium/hub:3.141.59-vanadium
      container_name: selenium-hub
      ports:
          - 4444:4444
  chrome:
    image: selenium/node-chrome:3.141.59-vanadium
    container_name: selenium-chrome
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
volumes:
  mysql-data: