version: '3'
services:
  php:
    build: ./docker/php
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      # php.ini
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      # apache
      - ./docker/php/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - mysql
      - selenium
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: sample
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  selenium:
    image: selenium/standalone-chrome-debug:latest
    shm_size: 2g
    ports:
      - "4444:4444"
      - "5900:5900"
volumes:
  mysql-data: